CREATE DATABASE STORE
GO
USE STORE
GO

CREATE TABLE PRODUCTS
(
ID INT IDENTITY (1,1) PRIMARY KEY, 
CATEGORY NVARCHAR(100)NOT NULL,
MARK NVARCHAR(100)NOT NULL,
DESCRIPTION NVARCHAR(100)NOT NULL,
COST FLOAT NOT NULL
)
GO
SELECT*FROM PRODUCTS